// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CesiumMap: typeof import('./src/components/CesiumMap/index.vue')['default']
    Controls: typeof import('./src/components/Controls/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElRow: typeof import('element-plus/es')['ElRow']
    Layer: typeof import('./src/components/Controls/Layer/index.vue')['default']
    LayerManager: typeof import('./src/components/LayerManager/index.vue')['default']
    Measure: typeof import('./src/components/Controls/Measure/index.vue')['default']
    Other: typeof import('./src/components/Controls/Other/index.vue')['default']
    PanelMenu: typeof import('./src/components/PanelMenu/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Start: typeof import('./src/components/Controls/Start/index.vue')['default']
    Tileset: typeof import('./src/components/Controls/Tileset/index.vue')['default']
  }
}
